/**
 * Blockchain wrapper APIs.
 * the purpose of this application is to provide an application that makes all kind of blockchain operations more and more easier and chain agnostic.  Is is a multi-tenant application that can be used by multi client or tenant. Each client can create user\'s wallet and public address by given key like tenant id and user id. System store users private key securely under hsm key or mpc wallet.  Tanent can perform various blockchain operation such as contract create, contract verify, burn, mint, transfer and so on. In summary, this multi-tenant application provides a secure environment for tenants to manage their digital assets on specific blockchains, with the added security of a custody wallet system that stores private keys under HSM key and MPC wallet.  This should demonstrate all the possible comment annotations that are available to turn go code into a fully compliant swagger 2.0 spec
 *
 * OpenAPI spec version: 0.0.1
 * Contact: e.mersinli@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeployContractParameter } from '../models/DeployContractParameter';
import { HttpFile } from '../http/http';

export class DeployRequest {
    /**
    * ChainId should be the same with the system. It could be taken from block explorer like sepolia, ethereum, cosmos-mainnet, tokenfab-mainnet
    */
    'chainId': string;
    /**
    * For solidity, it sould be like a class name, for cosmos based chain is the free format.
    */
    'contractName': string;
    /**
    * Contract creator address. It should have gas coin related chain and it should be imported or created on the system.
    */
    'contractOwner': string;
    /**
    * Parameter on the github repo template. There is # parameter in the template.
    */
    'contractPatameters': Array<DeployContractParameter>;
    /**
    * Template name at github repo. For solidity: https://github.com/tokenfab/testnet-contracts/tree/main/templates For Cosmos: https://github.com/tokenfab/testnet-contracts/tree/main/templates/wasm
    */
    'contractTemplate': string;
    /**
    * Manage Type is values 1: Coin 2: Token, 3: Nft
    */
    'manageType': string;
    /**
    * Token precision
    */
    'precision': number;
    /**
    * TokenName is the token short name like GOLD, USD, USDT
    */
    'tokenName': string;
    /**
    * the key given by client with any unique number to take response with that key. If not use you may set empty. Use it to take asynch response.
    */
    'txKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractName",
            "baseName": "contractName",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractOwner",
            "baseName": "contractOwner",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractPatameters",
            "baseName": "contractPatameters",
            "type": "Array<DeployContractParameter>",
            "format": ""
        },
        {
            "name": "contractTemplate",
            "baseName": "contractTemplate",
            "type": "string",
            "format": ""
        },
        {
            "name": "manageType",
            "baseName": "manageType",
            "type": "string",
            "format": ""
        },
        {
            "name": "precision",
            "baseName": "precision",
            "type": "number",
            "format": "int16"
        },
        {
            "name": "tokenName",
            "baseName": "tokenName",
            "type": "string",
            "format": ""
        },
        {
            "name": "txKey",
            "baseName": "txKey",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeployRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

